[tool.poetry]
name = "mortgage_mage"
version = "0.1.0"
description = "A financial modeler for mortgaged rental property"
authors = ["Jake Schmidt <schmidt.jake.c@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
numpy = "^1.21.2"
numpy-financial = "^1.0.0"
pandas = "^1.3.3"
requests = "^2.26.0"
structlog = "^21.1.0"

[tool.poetry.dev-dependencies]
colorama = "^0.4.4"
notebook = "^6.4.4"
seaborn = "^0.11.2"
pre-commit = "^2.15.0"
flake8 = "^3.9.2"
mypy = "^0.910"
black = "^21.9b0"
isort = "^5.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.mypy]
python_version = 3.8
ignore_missing_imports = true
exclude = ".venv"

[tool.black]
line-length = 88
target-version = ["py38"]
