[tool.poetry]
name = "mortgage_mage"
version = "0.1.0"
description = "A financial modeler for mortgaged rental property"
authors = ["Jake Schmidt <schmidt.jake.c@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
numpy = "^1.21.2"
numpy-financial = "^1.0.0"
pandas = "^1.3.3"
requests = "^2.26.0"
structlog = "^21.1.0"
xarray = "^0.19.0"
tenacity = "^8.0.1"

[tool.poetry.dev-dependencies]
colorama = "^0.4.4"
notebook = "^6.4.4"
seaborn = "^0.11.2"
pre-commit = "^2.15.0"
flake8 = "^3.9.2"
mypy = ">0.910"
black = "^21.9b0"
isort = "^5.9.3"
pyproject-flake8 = "^0.0.1-alpha.2"
types-requests = "^2.27.11"
bandit = "^1.7.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 120

[tool.isort]
profile = "black"
py_version = "auto"

[tool.mypy]
python_version = 3.8
ignore_missing_imports = true
strict = true
exclude = ".venv"

[tool.black]
line-length = 120
target-version = ["py38"]
