name: Checks and tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    name: Python ${{ matrix.python-version }} checks
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project dependencies
        run: |
          pip install -U pip
          pip install poetry
          poetry install --no-root
          poetry shell
      - name: Check pyproject.toml
        run: poetry check
      - name: Check import sorting
        run: |
          isort --settings-path=pyproject.toml --check-only .
      - name: Run flake8
        run: |
          pflake8 --config=pyproject.toml .
      - name: Format with black
        run: |
          black --config=pyproject.toml --check .
      - name: Run mypy
        run: |
          mypy --config-file=pyproject.toml .
      - name: Run tests
        run: |
          poetry run pytest tests/
